import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#fff8f7",
        "surface-dim": "#f1d3d0",
        "surface-bright": "#fff8f7",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#fff0ef",
        "surface-container": "#ffe9e7",
        "surface-container-high": "#ffe2de",
        "surface-container-highest": "#f9dcd9",
        "on-surface": "#271816",
        "on-surface-variant": "#5b403d",
        "inverse-surface": "#3e2c2a",
        "inverse-on-surface": "#ffedeb",
        "outline": "#8f6f6c",
        "outline-variant": "#e4beba",
        "surface-tint": "#ba1a20",
        "primary": "#af101a",
        "on-primary": "#ffffff",
        "primary-container": "#d32f2f",
        "on-primary-container": "#fff2f0",
        "inverse-primary": "#ffb3ac",
        "secondary": "#005db7",
        "on-secondary": "#ffffff",
        "secondary-container": "#64a1ff",
        "on-secondary-container": "#003670",
        "tertiary": "#715300",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#8f6a00",
        "on-tertiary-container": "#fff3e3",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffdad6",
        "primary-fixed-dim": "#ffb3ac",
        "on-primary-fixed": "#410003",
        "on-primary-fixed-variant": "#930010",
        "secondary-fixed": "#d6e3ff",
        "secondary-fixed-dim": "#a9c7ff",
        "on-secondary-fixed": "#001b3d",
        "on-secondary-fixed-variant": "#00468c",
        "tertiary-fixed": "#ffdfa0",
        "tertiary-fixed-dim": "#f8bd2a",
        "on-tertiary-fixed": "#261a00",
        "on-tertiary-fixed-variant": "#5c4300",
        "background": "#fff8f7",
        "on-background": "#271816",
        "surface-variant": "#f9dcd9",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        md: "0.375rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        "margin-mobile": "16px",
        gutter: "24px",
        "margin-desktop": "32px",
        "container-max": "1280px",
        "stack-sm": "12px",
        "stack-md": "24px",
        "stack-lg": "48px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        headline: ["Montserrat", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "headline-lg-mobile": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};

export default config;
